version: "3"

services:

  neuroglancer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - nginx
      - tomcat
    command: npm run dev-server
    ports:
      - "8091:8091"
    volumes:
      - neuroglancer:/app
    networks:
      - ng_networks

  mysql:
    image: 'mysql:5.7'
    ports:
      - "3306:3306" 
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - 'mysql:/var/lib/mysql'
      #- 'dumps:/dumps'
    networks:
      - ng_networks

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "82:82"
    networks:
      - ng_networks
    volumes: 
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  tomcat:
    #image: 'tomcat:8.5'
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8085:8080"
    volumes:
      - ./tomcat/web.xml:/usr/local/tomcat/conf/web.xml
      - ./tomcat/webroot:/usr/local/tomcat/webapps
    #links:
    #  - mysql
    #restart: always
    networks:
      - ng_networks

networks:
   ng_networks:
     driver: bridge


volumes:
  dumps:
  #postgres:
  mysql:
  nginx:
  neuroglancer:
  tomcat: